apiVersion: apps/v1
kind: Deployment
metadata:
  name: Api-deployment
  labels:
    env: app
spec:
  replicas: 1
  selector:
    matchLabels:
      env: app
  template:
    metadata:
      labels:
        env: app
    spec:
      containers:
        - name: Api
          image: 669364752626.dkr.ecr.us-east-1.amazonaws.com/api
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: Api-config